// Code generated by automake; DO NOT EDIT.

package i18n

const (
	Name = iota
	Address
	Age
)

const (
	enStr = "Hello 11 {{.Name}}street21"
	zhStr = "你好 {{.Name}}街道21"
)

var (
	enIndex = []uint{0, 18, 24, 26}
	zhIndex = []uint{0, 16, 22, 24}
)


func Translate(local string, index int, args ...string) string {
	if local == "en" {
		return enStr[enIndex[index]:enIndex[index+1]]
	}
	if local == "zh" {
		return zhStr[zhIndex[index]:zhIndex[index+1]]
	}

	return ""
}
